Problem 1


Question no 1.

In [1]:
import numpy as np
A=np.empty((2,2))
print(A)

[[4.92224508e-310 0.00000000e+000]
 [6.78629700e-310 6.78629687e-310]]


Question no 2.


In [2]:
import numpy as np
A = np.ones((4,2))
print(A)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Question no 3.


In [3]:
import numpy as np
filled = np.full((2,2),1)#2*2 matrix filled by 1 as the value
print(filled)

[[1 1]
 [1 1]]


Question no 4.


In [4]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
zero_arr = np.zeros_like(arr)
print(zero_arr)

[[1 2 3]
 [4 5 6]]
[[0 0 0]
 [0 0 0]]


Question no 5.


In [5]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
ones_arr = np.ones_like(arr)
print(ones_arr)

[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [1 1 1]]


Question no 6.


In [6]:
import numpy as np
new_list=[1,2,3,4,5]
arr = np.array(new_list)
print(arr)

[1 2 3 4 5]


Problem 2

Question no 1.


In [7]:
import numpy as np
arr = np.arange(10,49)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


Question no 2.

In [8]:
import numpy as np
arr = np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Question no 3.

In [9]:
import numpy as np
arr = np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Question no 4.


In [10]:
import numpy as np
arr = np.random.random(30)
print(arr)
arr_mean = arr.mean()
print("\n", arr_mean)

[0.56869832 0.72334855 0.13219117 0.2289333  0.45688852 0.05369531
 0.65812176 0.57916473 0.13282693 0.71282212 0.3510628  0.27919006
 0.2284547  0.39927326 0.13073009 0.83147532 0.52290753 0.545453
 0.15273939 0.43007274 0.90433034 0.87372332 0.24543007 0.1421478
 0.52692425 0.64440792 0.13362988 0.8019675  0.36748109 0.61238159]

 0.4456824455975212


Question no 5.

In [11]:
import numpy as np
arr = np.random.random((10,10))
print(arr)
arr_min = arr.min()
arr_max = arr.max()
print("\n", arr_min, arr_max)

[[5.66875036e-01 2.58772094e-01 2.81045849e-01 9.16637592e-01
  1.56966497e-02 8.49486227e-01 7.00257291e-01 1.91843760e-01
  7.40933226e-01 8.52957012e-01]
 [3.35192073e-01 1.02298855e-01 9.14728220e-02 9.95574064e-01
  1.23631656e-01 2.81977505e-01 3.73963994e-01 1.48038684e-01
  9.08260781e-01 4.43279865e-01]
 [3.30324662e-01 1.99578621e-01 9.49074335e-01 4.89835584e-01
  5.26637114e-01 7.47361317e-01 6.85517880e-01 9.68539610e-01
  5.61261745e-01 7.93941788e-01]
 [5.57957249e-01 3.32319063e-01 3.88276434e-01 9.04809232e-02
  3.75223155e-01 4.48310349e-04 5.39168179e-01 4.97731843e-01
  4.86846785e-01 4.55812501e-01]
 [7.97920623e-01 1.62841931e-01 6.23657095e-01 2.58919554e-01
  3.21442437e-01 4.71280966e-01 2.38138539e-01 4.12578853e-01
  9.51840568e-01 3.08210015e-02]
 [4.36818300e-01 6.28206909e-01 7.72786302e-01 4.60192366e-01
  2.64656862e-01 5.60416602e-02 5.38800317e-01 9.27926216e-01
  7.60090921e-01 7.65324382e-01]
 [2.92761628e-01 2.55969425e-01 9.17455513e-01 8.74615242e

Question no 6.

In [12]:
import numpy as np
arr = np.zeros(10)
arr[4] = 1
print (arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Question no 7.

In [13]:
import numpy as np
arr = [1,2,0,0,4,0]
rev_arr = np.flip(arr)
print(rev_arr)

[0 4 0 0 2 1]


Question no 8.

In [14]:
import numpy as np
arr = np.ones((4,4))
print("original array: \n", arr)
arr[1:-1,1:-1] = 0
print("Array with 1 on the border and 0 on inside \n", arr)

original array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array with 1 on the border and 0 on inside 
 [[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


Problem 3

In [15]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
sum_x_y = x+y
sum_v_w = v+w
print("sum of x and y matrix: \n",sum_x_y,"\n")
print("sum of v and w matirx: \n",sum_v_w, "\n")
diff_x_y = x-y
diff_v_w = v-w
print("difference of x and y matrix: \n",diff_x_y,"\n")
print("difference of v and w matrix: \n",diff_v_w, "\n")
prod_x_y = x*y
prod_v_w = v*w
print("product of x and y matrix: \n",prod_x_y,"\n")
print("product of v and w matrix: \n",prod_v_w, "\n")
sqr_x = np.square(x)
sqr_y = np.square(y)
sqr_v = np.square(v)
sqr_w = np.square(w)
print("square of x matrix: \n",sqr_x,"\n")
print("square of y matrix: \n",sqr_y,"\n")
print("square of v matrix: \n",sqr_v,"\n")
print("square of w matrix: \n",sqr_w,"\n")
dot_x_y = np.dot(x,y)
dot_v_w = np.dot(v,w)
print("dot product of x and y matrix: \n",dot_x_y,"\n")
print("dot product of v and w matrix: \n",dot_v_w,"\n")
conc1=np.concatenate((x,y),axis=1)
conc1
conc2=np.concatenate((v,w), axis=0)
conc2

sum of x and y matrix: 
 [[ 6  8]
 [10 13]] 

sum of v and w matirx: 
 [20 22] 

difference of x and y matrix: 
 [[-4 -4]
 [-4 -3]] 

difference of v and w matrix: 
 [-2 -2] 

product of x and y matrix: 
 [[ 5 12]
 [21 40]] 

product of v and w matrix: 
 [ 99 120] 

square of x matrix: 
 [[ 1  4]
 [ 9 25]] 

square of y matrix: 
 [[25 36]
 [49 64]] 

square of v matrix: 
 [ 81 100] 

square of w matrix: 
 [121 144] 

dot product of x and y matrix: 
 [[19 22]
 [50 58]] 

dot product of v and w matrix: 
 219 



array([ 9, 10, 11, 12])

Problem 4

In [17]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

inverse=np.linalg.inv(A)
mult=np.dot(A,inverse)

Equal1=np.dot(A,B)
Equal2=np.dot(B,A)
Equal3=Equal1==Equal2

inverse1=np.transpose(Equal1)
inverse2=np.transpose(B)
inverse3=np.transpose(A)
inverse4=np.dot(inverse2,inverse3)